name: bayes_book
channels:
  - conda-forge
dependencies:
  - arviz
  - jupyter
  - jupyterlab
  - jupytext
  - libblas=*=*mkl
  - matplotlib
  - mkl-service
  - myst-nb
  - myst-parser
  - numpy
  - pandas
  - pip
  - pymc3
  - python-graphviz
  - sphinx>3
  - sphinx-book-theme
  - watermark
  - pip:
    - sphinxcontrib-bibtex

