#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Bayes book documentation build configuration file

import arviz

arviz.rcParams["data.load"] = "eager"
arviz.Numba.disable_numba()

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '3.0'

extensions = [
    "sphinx.ext.mathjax",
    "sphinxcontrib.bibtex",
    "myst_nb",
]

# ipython directive configuration
ipython_warning_is_error = False

# MyST related params
jupyter_execute_notebooks = "cache"
execution_timeout = 120
myst_heading_anchors = 4

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "bayes book"
copyright = "2020, Alex Andorra & Oriol Abril"
author = "Alex Andorra & Oriol Abril"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# Extra sphinx configuration options
todo_include_todos = True
numfig = True # allow using numref to get reference numbers instead of title of reference

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ["_static"]

# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]
